CREATE TABLE config(
	key TEXT PRIMARY KEY,
	value TEXT NOT NULL
);
CREATE TABLE root (
	directory_id INTEGER PRIMARY KEY REFERENCES directory(id) ON DELETE CASCADE
);

CREATE TABLE directory (
	id INTEGER PRIMARY KEY,
	path TEXT NOT NULL UNIQUE,
	checked BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE file (
	name TEXT NOT NULL,
	directory_id INTEGER NOT NULL,
	last_modified INTEGER NOT NULL,
	size INTEGER NOT NULL,
	hash TEXT NOT NULL,
	PRIMARY KEY(name, directory_id),
	FOREIGN KEY(directory_id) REFERENCES directory(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS file_hash_ix ON file(hash);

